# Generated by Django 6.0.4 on 2026-05-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('documento', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('area', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('puntaje', models.IntegerField(default=0)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
