# Generated by Django 6.0.4 on 2026-05-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='area',
            field=models.CharField(choices=[('Tecnologia', 'Tecnología'), ('Calidad', 'Calidad'), ('Contabilidad', 'Contabilidad'), ('Tesoreria', 'Tesorería'), ('Costos', 'Costos'), ('Financiera', 'Financiera')], default='Tecnologia', max_length=20),
        ),
    ]
