# Generated by Django 6.0.4 on 2026-05-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0002_alter_evaluacion_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='tipo_examen',
            field=models.CharField(choices=[('limpieza', 'Limpieza y Desinfección'), ('bph', 'Buenas Prácticas Higiénicas (BPH)')], default='limpieza', max_length=50),
        ),
    ]
