# Generated by Django 6.0.4 on 2026-05-20 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0003_evaluacion_tipo_examen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Limpieza y Desinfección', max_length=200)),
                ('puntaje_minimo', models.IntegerField(default=7)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número de la pregunta (1, 2, 3...)')),
                ('texto', models.TextField(help_text='Texto de la pregunta')),
                ('opcion_a', models.CharField(max_length=255)),
                ('opcion_b', models.CharField(max_length=255)),
                ('opcion_c', models.CharField(blank=True, max_length=255, null=True)),
                ('opcion_d', models.CharField(blank=True, max_length=255, null=True)),
                ('respuesta_correcta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='recursos_humanos.examen')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
