# Generated by Django 6.0.4 on 2026-05-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0004_examen_pregunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='Numero de documento')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
            ],
        ),
    ]
