# Generated by Django 6.0.4 on 2026-05-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPlagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importancia', models.CharField()),
                ('tipo_plaga', models.CharField()),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
