# Generated by Django 6.0.4 on 2026-05-25 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plagas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroplagas',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='registroplagas',
            name='importancia',
        ),
        migrations.AddField(
            model_name='registroplagas',
            name='area',
            field=models.CharField(choices=[('FERMENTOS', 'Fermentos'), ('CAVAS', 'Cavas'), ('MUELLE DE CARGA', 'Muelle de Carga'), ('PASTEURIZACIÓN', 'Pasteurización'), ('MEZCLAS', 'Mezclas'), ('UHT', 'UHT'), ('QUESERA', 'Quesera'), ('BODEGA LOGISTICA', 'Bodega Logística'), ('CUARTOS FRIOS PRODUCTO TERMINADO', 'Cuartos Fríos Producto Terminado'), ('BODEGA MATERIA PRIMA', 'Bodega Materia Prima'), ('ACOPIO RESIDUOS SÓLIDOS', 'Acopio Residuos Sólidos'), ('PULVERIZADORA', 'Pulverizadora')], default=0, max_length=100, verbose_name='Área Afectada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroplagas',
            name='cedula',
            field=models.CharField(default=0, max_length=20, verbose_name='Cédula del Reportante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroplagas',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to='evidencias_plagas/', verbose_name='Archivo de Evidencia'),
        ),
        migrations.AddField(
            model_name='registroplagas',
            name='plaga',
            field=models.CharField(choices=[('Plagas rastreras', [('Cucarachas', 'Cucarachas'), ('Hormigas', 'Hormigas'), ('Escarabajos', 'Escarabajos'), ('Arañas', 'Arañas'), ('Lepismas', 'Lepismas (pececillos de plata)')]), ('Plagas voladoras', [('Moscas', 'Moscas'), ('Mosquitos', 'Mosquitos'), ('Polillas', 'Polillas'), ('Avispas', 'Avispas'), ('Abejas', 'Abejas')]), ('Plagas roedoras', [('Ratón doméstico', 'Ratón doméstico'), ('Rata gris', 'Rata gris'), ('Rata negra', 'Rata negra')])], default=0, max_length=50, verbose_name='Plaga Específica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroplagas',
            name='prioridad',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='', max_length=20, verbose_name='Prioridad/Severidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registroplagas',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción del Problema'),
        ),
        migrations.AlterField(
            model_name='registroplagas',
            name='fecha_hora',
            field=models.DateTimeField(verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='registroplagas',
            name='tipo_plaga',
            field=models.CharField(choices=[('Rastreras', 'Plagas rastreras'), ('Voladoras', 'Plagas voladoras'), ('Roedoras', 'Plagas roedoras')], max_length=50, verbose_name='Tipo de Plaga'),
        ),
        migrations.CreateModel(
            name='TicketPlaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
                ('hora_inicio', models.DateTimeField()),
                ('hora_final', models.DateTimeField()),
                ('descripcion_solucion', models.TextField()),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_plagas.registroplagas')),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('mensaje', models.CharField()),
                ('media', models.FileField(upload_to='')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_plagas.ticketplaga')),
            ],
        ),
    ]
