# Generated by Django 6.0.4 on 2026-05-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plagas', '0002_remove_registroplagas_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroplagas',
            name='fecha_hora',
            field=models.DateTimeField(auto_created=True, verbose_name='Fecha y Hora'),
        ),
    ]
