# Generated by Django 6.0.4 on 2026-05-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plagas', '0003_alter_registroplagas_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroplagas',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora'),
        ),
    ]
