# Generated by Django 6.0.4 on 2026-05-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plagas', '0004_alter_registroplagas_fecha_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatticket',
            name='usuario',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
