# Generated by Django 6.0.4 on 2026-05-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plagas', '0005_chatticket_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatticket',
            name='usuario_rol',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
