# Generated by Django 4.2.18 on 2026-02-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aforo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_silo', models.IntegerField()),
                ('hora_registro', models.DateField()),
                ('altura', models.FloatField()),
                ('densidad', models.FloatField()),
                ('vol_litros', models.FloatField()),
                ('kg_total', models.FloatField()),
                ('porcentage_llenado', models.FloatField()),
                ('lts_actuales', models.FloatField()),
                ('lts_disponibles', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Aforos',
            },
        ),
    ]
