# Generated by Django 4.2.28 on 2026-02-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aforo_silos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aforo',
            name='lts_actuales',
        ),
        migrations.AddField(
            model_name='aforo',
            name='imagen',
            field=models.ImageField(default=0, upload_to='imgs_evidencia/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aforo',
            name='hora_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
