# Generated by Django 4.2.28 on 2026-02-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aforo_silos', '0002_remove_aforo_lts_actuales_aforo_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aforo',
            name='num_silo',
            field=models.CharField(max_length=20),
        ),
    ]
