# Generated by Django 4.2.28 on 2026-03-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aforo_silos', '0003_alter_aforo_num_silo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(max_length=50)),
                ('comentarios', models.CharField(max_length=200)),
                ('hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Soporte',
            },
        ),
    ]
