# Generated by Django 4.2.28 on 2026-03-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aforo_silos', '0004_modelsoporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsoporte',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelsoporte',
            name='respuesta',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
