# Generated by Django 4.2.28 on 2026-03-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_colfrance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='emoji',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
