# Generated by Django 6.0.4 on 2026-05-04 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_colfrance', '0003_contacto_vacantes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='email',
            new_name='correo',
        ),
    ]
